### PR TITLE
Remove Decimal usage

### LINKED ISSUE #10: JSON conversion error
I am getting an error `TypeError: Object of type 'Decimal' is not JSON serializable` while attempting to write the results of the `shm` rule.

### PR DESCRIPTION
**Pull request by nikola-rados**
This PR removes the `Decimal` usage in favour of `float`. This resolves #10.

### CODE REVIEW

**Comment by corviday** [comment]
One thing I've run into that isn't actually related to this PR is that `requirements.txt` calls for `ce==3.1.0`. 

That version of the CE backend calls for `gdal~=3.0`

But `setup.py` calls for `GDAL==2.2`

I had to change the GDAL version in `setup.py` to 3.0 to be able to install the `p2a_impacts` package. 

Possibly the incompatible gdal requirements should be their own issue.

**Comment by nikola-rados** [comment]
I actually meant to take `GDAL` out of the requirements for this project and just let the `ce` handle the version. I'll change that now.

**Comment by corviday** [comment]
Seems like a good solution. p2a doesn't care what version of gdal it has and never uses it directly. Might as well let ce sort gdal out however it wants.

**Comment by nikola-rados** [comment]
The `ci` is being really fussy about `gdal`. I think this should be a separate issue. Is the rest of this PR good to go though?

**Review by corviday — APPROVED** [review]
LGTM

**Pull request merged**
